// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg struct {
	Datas                []*Row   `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetDatas() []*Row {
	if m != nil {
		return m.Datas
	}
	return nil
}

type Row struct {
	StdID                string   `protobuf:"bytes,1,opt,name=stdID,proto3" json:"stdID,omitempty"`
	KeyNo                string   `protobuf:"bytes,2,opt,name=keyNo,proto3" json:"keyNo,omitempty"`
	Status1              string   `protobuf:"bytes,3,opt,name=status1,proto3" json:"status1,omitempty"`
	Status2              string   `protobuf:"bytes,4,opt,name=status2,proto3" json:"status2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetStdID() string {
	if m != nil {
		return m.StdID
	}
	return ""
}

func (m *Row) GetKeyNo() string {
	if m != nil {
		return m.KeyNo
	}
	return ""
}

func (m *Row) GetStatus1() string {
	if m != nil {
		return m.Status1
	}
	return ""
}

func (m *Row) GetStatus2() string {
	if m != nil {
		return m.Status2
	}
	return ""
}

func init() {
	proto.RegisterType((*Msg)(nil), "pb.msg")
	proto.RegisterType((*Row)(nil), "pb.row")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe1, 0x62, 0xce, 0x2d, 0x4e,
	0x17, 0x92, 0xe5, 0x62, 0x4d, 0x49, 0x2c, 0x49, 0x2c, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36,
	0x62, 0xd7, 0x2b, 0x48, 0xd2, 0x2b, 0xca, 0x2f, 0x0f, 0x82, 0x88, 0x2a, 0xa5, 0x72, 0x31, 0x17,
	0xe5, 0x97, 0x0b, 0x89, 0x70, 0xb1, 0x16, 0x97, 0xa4, 0x78, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x41, 0x38, 0x20, 0xd1, 0xec, 0xd4, 0x4a, 0xbf, 0x7c, 0x09, 0x26, 0x88, 0x28, 0x98,
	0x23, 0x24, 0xc1, 0xc5, 0x5e, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x6c, 0x28, 0xc1, 0x0c, 0x16, 0x87,
	0x71, 0x11, 0x32, 0x46, 0x12, 0x2c, 0xc8, 0x32, 0x46, 0x49, 0x6c, 0x60, 0x77, 0x19, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x89, 0x90, 0x12, 0x90, 0xa4, 0x00, 0x00, 0x00,
}
